### ISSUE TITLE
Basic example not working

### ISSUE THREAD

**Issue by 0zirix** [microsoft/merklecpp#11]
Hello,

I noticed that the original example provided in the main documentation page of the repo isn't working.

For example, the `path` method which is present on the tree structure, doesn't return a reference but a pointer... which makes this line in the example wrong: 
```
auto path = tree.path(0);
assert(path.verify(root));
```

Which should be:
```
auto path = tree.path(0);
assert(path->verify(root));
```

But even if we fix this little issue, another come just after (with the VS compiler in my case), which comes from the line 
https://github.com/microsoft/merklecpp/blob/b60a482187906394a521c03536ce7a3274a710cd/merklecpp.h#L115

After some research, the problem comes from the hash size passed in parameters, the hash should be of size 32bits, but the provided example only provide a string "message", which is not 32bits, hence making the example crash.

I think this should be explained in the documentation, because it's not obvious that the string should be 32 bits.

**Comment by achamayou** [comment]
@0zirix thank you for spotting this, it should be fixed now.

**Comment by wintersteiger** [comment]
Awesome, thanks for fixing this @achamayou!
