### ISSUE TITLE
The size of the serialization path is wrong

### ISSUE THREAD

**Issue by therainisme** [microsoft/merklecpp#19]
Hello! The size returned by the serialised_size() method of the path is inconsistent with the actual serialization size.

```cpp
int main() {
  merkle::Tree::Hash hash("fa8f44eabb728d4020e7f33d1aa973faaef19de6c06679bccdc5100a3c01f54a");
  merkle::Tree tree;
  tree.insert(hash);
  auto root = tree.root();
  auto path = tree.path(0);

  std::cout << path->serialised_size() << std::endl;
  // output: 32

  std::vector<uint8_t> serialised_path;
  path->serialise(serialised_path);
  std::cout << serialised_path.size() << std::endl;
  // output: 56

  return 0;
}
```

**Comment by achamayou** [comment]
@therainisme thank you for reporting this, there was definitely a mistake there. Address in #19.

**Comment by achamayou** [comment]
https://github.com/microsoft/merklecpp/releases/tag/v1.1.1

**Comment by therainisme** [comment]
> https://github.com/microsoft/merklecpp/releases/tag/v1.1.1

Thank you so much for addressing the issue promptly!
